### ISSUE TITLE
Not identifying "`" regions as css

### ISSUE THREAD

**Issue by Jmeyering** [fleischie/vim-styled-components#20]

**Comment by Jmeyering** [comment]
![image](https://cloud.githubusercontent.com/assets/5166603/26517234/07794aaa-425a-11e7-84e6-d5c75462cec0.png)

As you can see I'm really struggling to get this syntax working properly. You can see my .vimrc here
https://github.com/Jmeyering/dotfiles/blob/master/vimrc.

Interestingly enough with this screenshot as you can see I do get appropriate highlighting of the regions enclosed in the `${}`.

Any thoughts on what I may be doing wrong here?

**Comment by Jmeyering** [comment]
I'm running Vim 7.4 in Ubuntu with Solarized Dark

**Comment by fleischie** [comment]
Hello.

If I understand correctly you are referring to the first three attributes, right? Because I can assure you, that this is not your fault. This is an issue I had troubles with getting correctly implemented.

To be more specific: Css has a `CSSAttrRegion`, that matches keywords up until a `:`. Unfortunately this leads to pseudo-elements and -classes to be misinterpreted. Leaving this rule out means certain definitions with hyphens, keywords that are both attributes and props, and certain other cases may be highlighted incorrectly.

But I am definitely not content with that and am going to investigate this. I had some ideas on how to cope with this (see #18) but unfortunately I did not have much time, yet.

**Comment by Jmeyering** [comment]
Correct! Good to know! Thanks for the information

**Comment by fleischie** [comment]
@Jmeyering what version are you using? (Or more specifically, when did you last update this plugin?)

Because I just added the code snippet from your issue and I cannot reproduce your observed behavior/highlighting.

<img width="435" alt="screen shot 2017-05-29 at 23 17 00" src="https://cloud.githubusercontent.com/assets/2211050/26562247/fa8152b2-44c4-11e7-915d-5b3d5ce7fe15.png">

I use the latest develop-branch with iTerm2, your vimrc, and plugins. So the issue is still valid (to some extend) but I don't know, whether this is as applicable to the issue you reported or not.


Let me know if there is anything else you expect/-ed or whether this is not the answer you were looking for or anything you have on your mind about this issue. Feedback is necessary to progress this. 💪

**Comment by Jmeyering** [comment]
So interestingly I was on vim 7.4. I upgraded to 8.0 and now my syntax looks as yours does.

So hopefully that helps someone else.

**Comment by fleischie** [comment]
Ooohhh.

This might have to do with the standard CSS rules, that are shipped with vim. I will check, whether 8 has more/different rules than 7.4 (and neovim).

In any case this might be very helpful. Thank you for reporting and feedbacking (backfeeding?). 🙇

**Comment by fleischie** [comment]
@Jmeyering should I still investigate this issue? I would like to close this specific one and wait for another (similar) issue to reference this one and perhaps go from there, if you say you don't have this problem anymore. :smile:

In any other case. I might dig deeper into this.

**Comment by Jmeyering** [comment]
works for me
